version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: order_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order
    ports:
      - "5450:5432"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_broker
    restart: always
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # RabbitMQ Management UI